-- Script: 001_create_schemas.sql
-- Purpose: Create TMS_APP schema and grant privileges
-- Date: 2026-07-20
-- Author: Your Name
-- TDS §2.2: One schema per application

BEGIN
   EXECUTE IMMEDIATE 'DROP USER TMS_APP CASCADE';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

-- Create TMS_APP schema (application owner)
CREATE USER TMS_APP IDENTIFIED BY "TmsDevPass123!";

-- Grant essential privileges
GRANT CREATE SESSION TO TMS_APP;
GRANT CREATE TABLE TO TMS_APP;
GRANT CREATE PROCEDURE TO TMS_APP;
GRANT CREATE VIEW TO TMS_APP;
GRANT CREATE SEQUENCE TO TMS_APP;
GRANT UNLIMITED TABLESPACE TO TMS_APP;
GRANT CREATE JOB TO TMS_APP;

-- Apex-related grants
GRANT EXECUTE ON APEX_API_EXTENSION TO TMS_APP;

COMMIT;

PROMPT TMS_APP schema created successfully.